[project]
name = "cryptomeria-py"
dynamic = ["version"]
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
dev = ["ruff>=0.6.0"]

[tool.uv]
package = false

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.uv.sources]
cryptomeria = { path = "./python" }

[tool.ruff]
select = ["E", "F", "W", "C90"]
ignore = []
line-length = 88
target-version = "py313"
