CREATE TABLE IF NOT EXISTS trades (
    inst_id SYMBOL INDEX TYPE POSTING,
    trade_id SYMBOL,
    px DOUBLE,
    sz DOUBLE,
    side SYMBOL,
    exchange SYMBOL INDEX TYPE POSTING,
    ts TIMESTAMP
) TIMESTAMP(ts) PARTITION BY HOUR TTL 1 HOURS;