DROP TABLE IF EXISTS orderbook_snapshots;

CREATE TABLE IF NOT EXISTS lob_levels (
    inst_id SYMBOL INDEX TYPE POSTING,
    ts TIMESTAMP,
    action SYMBOL,
    side SYMBOL INDEX TYPE POSTING INCLUDE(price),
    price DOUBLE,
    size DOUBLE,
    count DOUBLE,
    orders DOUBLE,
    exchange SYMBOL INDEX TYPE POSTING
) TIMESTAMP(ts) PARTITION BY HOUR TTL 1 HOURS;